apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo-app
  description: The place to be, for great people
  links:
    - url: https://github.com/brahmdev/scania-backstage-app
      title: BackStage Demo App
      icon: code
  annotations:
    github.com/project-slug: 'brahmdev/scania-backstage-app'
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: development
  system: scania-backstage
  owner: demo-team
---
