site_name: 'Scania Backstage App'
site_description: 'Main documentation for Demo App'
plugins:
  - techdocs-core
nav:
  - Home: 'index.md'
  - Architecture: 'architecture.md'
  - Build & Deployment: 'buildAndDeployment.md'
  - Roadmap: 'roadmap.md'
